name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: dotnet test
        run: dotnet test tests/VisitedTraderTeleport.Tests/VisitedTraderTeleport.Tests.csproj -c Release

      - name: dotnet test (SdtdTestPilot)
        run: dotnet test tests/SdtdTestPilot.Tests/SdtdTestPilot.Tests.csproj -c Release
