name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-dotnet@v6
        with:
          dotnet-version: "8.0.x"

      - name: dotnet test
        run: dotnet test tests/VisitedTraderTeleport.Tests/VisitedTraderTeleport.Tests.csproj -c Release
